# Generated by Django 5.0.6 on 2024-06-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_notification_content_remove_notification_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(default='', max_length=100),
        ),
    ]
